# Generated by Django 4.0.6 on 2022-08-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210610_1442'),
        ('store', '0006_auto_20220723_1229'),
    ]

    operations = [
    ]
