# Generated by Django 4.0.6 on 2022-08-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_merge_0004_auto_20210610_1442_0006_auto_20220723_1229'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
